-- Legacy observability migration intentionally retired during the Phase 3 refactor.
-- Do not recreate the old `observability.logs`, `observability.api_failure_details`,
-- or `observability.error_details` tables.
--
-- Canonical observability references:
-- - docs/observability_refactor_policy.md
-- - apps/shared/observability/observability_tables_with_app_area.sql
--
-- The live model is:
-- - public.api_logs
-- - public.exception_logs
-- with required `app_area` on every persisted row.
