-- Legacy migration retired during Phase 3 cleanup.
-- The live booking schema was applied directly in a fresh database before launch,
-- and this file encoded the superseded pre-Phase-2 booking model.
-- Intentionally no-op so stale enums, constraints, and table definitions cannot be reintroduced.
