-- Legacy migration retired during Phase 3 cleanup.
-- The current booking side-effect intent set is defined by the Phase-2 model and
-- is already present in the fresh live schema.
-- Intentionally no-op so deprecated legacy intents are not reintroduced.
