-- Legacy migration retired during Phase 3 cleanup.
-- It encoded the superseded pre-Phase-2 status/event/effect vocabulary and must
-- not be applied against the fresh live booking schema.
-- Intentionally no-op.
